# SPDX-FileCopyrightText: 2026-2026 Franco Masotti (See /README.md)
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Will enable this once it's approved.
# github: frnmst
liberapay: frnmst
buy_me_a_coffee: frnmst
